version: '2.1'

services:
  workhooksbem:
    image: workhooksbem
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5500:5500
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 scripts/start.js